### ISSUE TITLE
https://www.geteventstore.com/ as a Projection/ReadModel target

### ISSUE THREAD

**Issue by tudobala** [broadway/broadway#211] opened 2015-09-08 21:04 UTC
I am considering writing a Projector that replicates all the domain events into the [geteventstore.com Event Store software](https://www.geteventstore.com/), since the Event Store supports extracting temporal information from the event stream and also different kind of projections written in Javascript, among other analysis. In essence, turning it into a powerful read model.

FYI: I did not consider making it the write model because of the HTTP interface (or lack of php lib calls).

Does this makes any sense?

**Comment by dgafka** [comment] 2015-09-10 06:04
Hey,
I wouldn't call event based store a powerful read model.
You need to read all events and recreate aggregate. (Probably implement memento pattern also)
Let's say you have mongodb as your write model feeded by PHP App. Now you reproduce events to eventstore, because you want to use it in some NodeJs App. 
1. You need to reimplement all your aggregates logic in NodeJs App, to recreate state from events.
2. You need to pull out from Read Model tons of events. Performance is bad, specially when you have alot of requests.
3. If you need integration with other server sided programming languages. Why not to implement some API in your PHP App, which other languages may consume?
4. Use EventStore as your Write Model. For now there is only HTTP interface, but I am working on Socket API, which is like 2-3 times faster. 
It will be merged into https://github.com/dbellettini/php-eventstore-client, when I finish it.

**Comment by dgafka** [comment] 2015-09-19 13:23
Hey again. 
EventStore TCP/IP Socket Client is available to use now:
https://packagist.org/packages/madkom/eventstore-client

Please report any bugs, if you find some :)

**Comment by othillo** [comment] 2017-02-24 14:10
Hi, I'm closing this. A (get)eventstore implementation is more that welcome. If someone wants to work on this, please, ping me and I will set you up with a separate repository.

**Closed by othillo** 2017-02-24 14:10 UTC
